name: Deploy On Dev
on:
  push:
    branches:
      - dev

env:
  ENVIRONMENT: dev
#  ACL_DOCKER_REPO_URL: europe-west4-docker.pkg.dev/ingka-orderpromise-acl-dev/acl-docker-repo
  TESTCONTAINERS_RYUK_DISABLED: true
permissions:
  contents: write
  id-token: write

jobs:
  deploy_on_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #################################
      ## Caching
      #################################

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go
        uses: actions/setup-go@v4 # v3.5.0
        with:
          cache: true
          go-version-file: 'go.mod'
          
      # Setup linter
      - name: Lint (info)
        id: linter
        run: echo "version=$(make lint-info)" >> $GITHUB_OUTPUT

      - name: Lint (cache)
        uses: actions/cache@v3 # v3.2.5
        with:
          path: |
            ${{ steps.linter.outputs.version }}
          key: ${{ runner.os }}-lint-${{ steps.linter.outputs.version }}

      #################################
      ## Set Alpha Version
      #################################
      # Prepare release version bumping previous tag and pushing new one
      # https://github.com/marketplace/actions/github-tag-bump
      - name: Bump Alpha version
        id: bump_version_generator
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
          INITIAL_VERSION: 0.0.0
          RELEASE_BRANCHES: master
          DEFAULT_BRANCH: master
          PRERELEASE_SUFFIX: alpha
          PRERELEASE: true
          DRY_RUN: true
          VERBOSE: true

      # Setting the Build Version
      - name: Set build version environment
        run: |
          echo "BUILD_VERSION=${{ steps.bump_version_generator.outputs.new_tag }}" >> $GITHUB_ENV
          echo "DEPLOYING ON DEV version ${{ env.BUILD_VERSION }}"

      - name: Build and verify application
        run: |
          make build \
          ENVIRONMENT=${{ env.ENVIRONMENT }} \
          VERSION=${{ env.BUILD_VERSION }} \


      #################################
      ## Create Tags
      #################################
      - name: Create tag for last alpha version
        run: |
          git tag ${{ env.BUILD_VERSION }}
          git push origin ${{ env.BUILD_VERSION }}
